/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "simple_cpu/simple_cpu.v:6.1-295.10" *)
module simple_cpu_golden(clk, rst, PC, Instruction, Address, MemWrite, Write_data, Write_strb, Read_data, MemRead);
  (* src = "simple_cpu/simple_cpu.v:193.41-193.51" *)
  wire [31:0] _000_;
  (* src = "simple_cpu/simple_cpu.v:281.23-281.41" *)
  wire [31:0] _001_;
  (* src = "simple_cpu/simple_cpu.v:284.21-284.39" *)
  wire [31:0] _002_;
  (* src = "simple_cpu/simple_cpu.v:290.21-290.27" *)
  wire [31:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire [4:0] _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  (* src = "simple_cpu/simple_cpu.v:150.46-150.78" *)
  wire _018_;
  (* src = "simple_cpu/simple_cpu.v:150.82-150.114" *)
  wire _019_;
  (* src = "simple_cpu/simple_cpu.v:175.28-175.60" *)
  wire _020_;
  (* src = "simple_cpu/simple_cpu.v:175.66-175.89" *)
  wire _021_;
  (* src = "simple_cpu/simple_cpu.v:175.140-175.163" *)
  wire _022_;
  (* src = "simple_cpu/simple_cpu.v:175.216-175.239" *)
  wire _023_;
  (* src = "simple_cpu/simple_cpu.v:175.293-175.316" *)
  wire _024_;
  (* src = "simple_cpu/simple_cpu.v:177.9-177.41" *)
  wire _025_;
  (* src = "simple_cpu/simple_cpu.v:178.9-178.41" *)
  wire _026_;
  (* src = "simple_cpu/simple_cpu.v:209.9-209.41" *)
  wire _027_;
  (* src = "simple_cpu/simple_cpu.v:210.9-210.41" *)
  wire _028_;
  (* src = "alu/alu.v:38.32-38.42" *)
  wire [32:0] _029_;
  (* src = "alu/alu.v:32.16-32.31" *)
  wire _030_;
  (* src = "alu/alu.v:32.37-32.56" *)
  wire _031_;
  (* src = "alu/alu.v:35.26-35.29" *)
  wire [31:0] _032_;
  (* src = "alu/alu.v:44.20-44.47" *)
  wire _033_;
  (* src = "alu/alu.v:69.46-69.67" *)
  wire [31:0] _034_;
  (* src = "alu/alu.v:69.72-69.94" *)
  wire [31:0] _035_;
  (* src = "alu/alu.v:69.32-69.95" *)
  wire [31:0] _036_;
  (* src = "alu/alu.v:70.22-70.45" *)
  wire _037_;
  (* src = "alu/alu.v:70.7-70.60" *)
  wire [31:0] _038_;
  (* src = "alu/alu.v:44.51-44.71" *)
  wire _039_;
  (* src = "alu/alu.v:44.23-44.46" *)
  wire _040_;
  (* src = "alu/alu.v:49.17-49.32" *)
  wire _041_;
  (* src = "reg_file/reg_file.v:21.2-25.5" *)
  wire [4:0] _042_;
  (* src = "reg_file/reg_file.v:21.2-25.5" *)
  wire [31:0] _043_;
  (* src = "reg_file/reg_file.v:21.2-25.5" *)
  wire [31:0] _044_;
  (* src = "reg_file/reg_file.v:22.7-22.19" *)
  wire _045_;
  (* src = "reg_file/reg_file.v:28.29-28.32" *)
  wire [31:0] _046_;
  (* src = "reg_file/reg_file.v:29.29-29.32" *)
  wire [31:0] _047_;
  (* src = "reg_file/reg_file.v:28.18-28.47" *)
  wire _048_;
  (* src = "reg_file/reg_file.v:29.18-29.47" *)
  wire _049_;
  (* src = "simple_cpu/simple_cpu.v:279.13-279.42" *)
  wire _050_;
  (* src = "simple_cpu/simple_cpu.v:150.26-150.40" *)
  wire _051_;
  (* src = "simple_cpu/simple_cpu.v:150.46-150.114" *)
  wire _052_;
  (* src = "simple_cpu/simple_cpu.v:153.20-153.34" *)
  wire _053_;
  (* src = "simple_cpu/simple_cpu.v:154.26-154.39" *)
  wire _054_;
  (* src = "simple_cpu/simple_cpu.v:154.26-154.47" *)
  wire _055_;
  (* src = "simple_cpu/simple_cpu.v:158.30-158.43" *)
  wire _056_;
  (* src = "simple_cpu/simple_cpu.v:158.30-158.51" *)
  wire _057_;
  (* src = "simple_cpu/simple_cpu.v:158.30-158.60" *)
  wire _058_;
  (* src = "simple_cpu/simple_cpu.v:158.30-158.67" *)
  wire _059_;
  (* src = "simple_cpu/simple_cpu.v:190.21-190.43" *)
  wire _060_;
  (* src = "simple_cpu/simple_cpu.v:190.21-190.51" *)
  wire _061_;
  (* src = "simple_cpu/simple_cpu.v:190.21-190.58" *)
  wire _062_;
  (* src = "simple_cpu/simple_cpu.v:190.21-190.67" *)
  wire _063_;
  (* src = "simple_cpu/simple_cpu.v:190.21-190.74" *)
  wire _064_;
  (* src = "simple_cpu/simple_cpu.v:191.24-191.36" *)
  wire _065_;
  (* src = "simple_cpu/simple_cpu.v:191.24-191.45" *)
  wire _066_;
  (* src = "simple_cpu/simple_cpu.v:191.24-191.54" *)
  wire _067_;
  (* src = "simple_cpu/simple_cpu.v:193.26-193.37" *)
  wire _068_;
  (* src = "simple_cpu/simple_cpu.v:246.18-246.61" *)
  wire _069_;
  (* src = "simple_cpu/simple_cpu.v:246.18-246.84" *)
  wire _070_;
  (* src = "simple_cpu/simple_cpu.v:157.83-157.103" *)
  wire _071_;
  (* src = "simple_cpu/simple_cpu.v:206.45-206.54" *)
  wire _072_;
  (* src = "simple_cpu/simple_cpu.v:208.45-208.59" *)
  wire _073_;
  (* src = "simple_cpu/simple_cpu.v:157.61-157.103" *)
  wire _074_;
  (* src = "simple_cpu/simple_cpu.v:159.64-159.111" *)
  wire _075_;
  wire [31:0] _076_;
  wire [31:0] _077_;
  wire [31:0] _078_;
  (* src = "simple_cpu/simple_cpu.v:182.61-182.189" *)
  wire [31:0] _079_;
  (* src = "simple_cpu/simple_cpu.v:183.64-183.122" *)
  wire [31:0] _080_;
  (* src = "simple_cpu/simple_cpu.v:185.61-185.86" *)
  wire [3:0] _081_;
  (* src = "simple_cpu/simple_cpu.v:152.45-152.70" *)
  wire [31:0] _082_;
  (* src = "simple_cpu/simple_cpu.v:154.25-156.34" *)
  wire [31:0] _083_;
  (* src = "simple_cpu/simple_cpu.v:155.25-156.34" *)
  wire [31:0] _084_;
  (* src = "simple_cpu/simple_cpu.v:158.29-159.137" *)
  wire [2:0] _085_;
  (* src = "simple_cpu/simple_cpu.v:159.29-159.137" *)
  wire [2:0] _086_;
  (* src = "simple_cpu/simple_cpu.v:175.292-175.374" *)
  wire [31:0] _087_;
  (* src = "simple_cpu/simple_cpu.v:175.215-175.374" *)
  wire [31:0] _088_;
  (* src = "simple_cpu/simple_cpu.v:175.139-175.374" *)
  wire [31:0] _089_;
  (* src = "simple_cpu/simple_cpu.v:175.65-175.374" *)
  wire [31:0] _090_;
  (* src = "simple_cpu/simple_cpu.v:176.8-179.176" *)
  wire [31:0] _091_;
  (* src = "simple_cpu/simple_cpu.v:176.122-176.204" *)
  wire [31:0] _092_;
  (* src = "simple_cpu/simple_cpu.v:176.46-176.204" *)
  wire [31:0] _093_;
  (* src = "simple_cpu/simple_cpu.v:177.8-179.175" *)
  wire [31:0] _094_;
  (* src = "simple_cpu/simple_cpu.v:178.157-178.263" *)
  wire [7:0] _095_;
  (* src = "simple_cpu/simple_cpu.v:178.107-178.263" *)
  wire [7:0] _096_;
  (* src = "simple_cpu/simple_cpu.v:178.58-178.263" *)
  wire [7:0] _097_;
  (* src = "simple_cpu/simple_cpu.v:178.8-179.174" *)
  wire [31:0] _098_;
  (* src = "simple_cpu/simple_cpu.v:178.208-178.263" *)
  wire [7:0] _099_;
  (* src = "simple_cpu/simple_cpu.v:179.108-179.164" *)
  wire [15:0] _100_;
  (* src = "simple_cpu/simple_cpu.v:179.58-179.164" *)
  wire [15:0] _101_;
  (* src = "simple_cpu/simple_cpu.v:179.8-179.173" *)
  wire [31:0] _102_;
  (* src = "simple_cpu/simple_cpu.v:182.153-182.188" *)
  wire [31:0] _103_;
  (* src = "simple_cpu/simple_cpu.v:182.121-182.188" *)
  wire [31:0] _104_;
  (* src = "simple_cpu/simple_cpu.v:182.89-182.188" *)
  wire [31:0] _105_;
  (* src = "simple_cpu/simple_cpu.v:183.45-183.131" *)
  wire [31:0] _106_;
  (* src = "simple_cpu/simple_cpu.v:183.7-184.61" *)
  wire [31:0] _107_;
  (* src = "simple_cpu/simple_cpu.v:184.7-184.61" *)
  wire [31:0] _108_;
  (* src = "simple_cpu/simple_cpu.v:186.64-186.101" *)
  wire [3:0] _109_;
  (* src = "simple_cpu/simple_cpu.v:186.45-186.112" *)
  wire [3:0] _110_;
  (* src = "simple_cpu/simple_cpu.v:186.7-187.58" *)
  wire [3:0] _111_;
  (* src = "simple_cpu/simple_cpu.v:187.7-187.58" *)
  wire [3:0] _112_;
  (* src = "simple_cpu/simple_cpu.v:192.25-193.59" *)
  wire [31:0] _113_;
  (* src = "simple_cpu/simple_cpu.v:193.25-193.59" *)
  wire [31:0] _114_;
  (* src = "simple_cpu/simple_cpu.v:206.8-210.70" *)
  wire _115_;
  (* src = "simple_cpu/simple_cpu.v:207.8-210.69" *)
  wire _116_;
  (* src = "simple_cpu/simple_cpu.v:208.8-210.68" *)
  wire _117_;
  (* src = "simple_cpu/simple_cpu.v:209.8-210.67" *)
  wire _118_;
  (* src = "simple_cpu/simple_cpu.v:210.8-210.66" *)
  wire _119_;
  (* src = "simple_cpu/simple_cpu.v:78.15-78.20" *)
  wire [31:0] ALU_A;
  (* src = "simple_cpu/simple_cpu.v:79.14-79.23" *)
  wire [2:0] ALU_ALUop;
  (* src = "simple_cpu/simple_cpu.v:78.22-78.27" *)
  wire [31:0] ALU_B;
  (* src = "simple_cpu/simple_cpu.v:80.8-80.20" *)
  wire ALU_Overflow;
  (* src = "simple_cpu/simple_cpu.v:78.29-78.39" *)
  wire [31:0] ALU_Result;
  (* src = "simple_cpu/simple_cpu.v:77.15-77.28" *)
  wire [31:0] ALU_Shifter_A;
  (* src = "simple_cpu/simple_cpu.v:200.15-200.33" *)
  wire [31:0] ALU_Shifter_Result;
  (* src = "simple_cpu/simple_cpu.v:50.15-50.37" *)
  reg [31:0] ALU_Shifter_Result_reg;
  (* src = "simple_cpu/simple_cpu.v:80.36-80.44" *)
  wire ALU_Zero;
  (* src = "simple_cpu/simple_cpu.v:36.8-36.13" *)
  wire AUIPC;
  (* src = "simple_cpu/simple_cpu.v:13.19-13.26" *)
  output [31:0] Address;
  wire [31:0] Address;
  (* src = "simple_cpu/simple_cpu.v:204.8-204.28" *)
  wire Branch_condition_met;
  (* src = "simple_cpu/simple_cpu.v:39.8-39.13" *)
  wire Btype;
  (* src = "simple_cpu/simple_cpu.v:11.19-11.30" *)
  input [31:0] Instruction;
  wire [31:0] Instruction;
  (* src = "simple_cpu/simple_cpu.v:48.14-48.29" *)
  reg [31:0] Instruction_reg;
  (* src = "simple_cpu/simple_cpu.v:42.8-42.13" *)
  wire Itype;
  (* src = "simple_cpu/simple_cpu.v:37.8-37.11" *)
  wire JAL;
  (* src = "simple_cpu/simple_cpu.v:38.8-38.12" *)
  wire JALR;
  (* src = "simple_cpu/simple_cpu.v:35.8-35.11" *)
  wire LUI;
  (* src = "simple_cpu/simple_cpu.v:40.8-40.12" *)
  wire Load;
  (* src = "simple_cpu/simple_cpu.v:19.19-19.26" *)
  output MemRead;
  wire MemRead;
  (* src = "simple_cpu/simple_cpu.v:14.19-14.27" *)
  output MemWrite;
  wire MemWrite;
  (* src = "simple_cpu/simple_cpu.v:10.19-10.21" *)
  output [31:0] PC;
  wire [31:0] PC;
  (* src = "simple_cpu/simple_cpu.v:53.15-53.21" *)
  reg [31:0] PC_reg;
  (* src = "simple_cpu/simple_cpu.v:61.14-61.24" *)
  wire [4:0] RF_radder1;
  (* src = "simple_cpu/simple_cpu.v:61.26-61.36" *)
  wire [4:0] RF_radder2;
  (* src = "simple_cpu/simple_cpu.v:62.15-62.24" *)
  wire [31:0] RF_rdata1;
  (* src = "simple_cpu/simple_cpu.v:62.26-62.35" *)
  wire [31:0] RF_rdata2;
  (* src = "simple_cpu/simple_cpu.v:58.15-58.23" *)
  wire [4:0] RF_waddr;
  (* src = "simple_cpu/simple_cpu.v:59.15-59.23" *)
  wire [31:0] RF_wdata;
  (* src = "simple_cpu/simple_cpu.v:57.15-57.21" *)
  wire RF_wen;
  (* src = "simple_cpu/simple_cpu.v:18.19-18.28" *)
  input [31:0] Read_data;
  wire [31:0] Read_data;
  (* src = "simple_cpu/simple_cpu.v:51.15-51.28" *)
  reg [31:0] Read_data_reg;
  (* src = "simple_cpu/simple_cpu.v:43.8-43.13" *)
  wire Rtype;
  (* src = "simple_cpu/simple_cpu.v:94.15-94.24" *)
  wire [31:0] Shifter_A;
  (* src = "simple_cpu/simple_cpu.v:95.14-95.23" *)
  wire [4:0] Shifter_B;
  (* src = "simple_cpu/simple_cpu.v:94.26-94.40" *)
  wire [31:0] Shifter_Result;
  (* src = "simple_cpu/simple_cpu.v:96.14-96.29" *)
  wire [1:0] Shifter_Shiftop;
  (* src = "simple_cpu/simple_cpu.v:41.8-41.13" *)
  wire Store;
  (* src = "simple_cpu/simple_cpu.v:15.19-15.29" *)
  output [31:0] Write_data;
  wire [31:0] Write_data;
  (* src = "simple_cpu/simple_cpu.v:16.19-16.29" *)
  output [3:0] Write_strb;
  wire [3:0] Write_strb;
  (* hdlname = "alu_main A" *)
  (* src = "alu/alu.v:6.23-6.24" *)
  wire [31:0] \alu_main.A ;
  (* hdlname = "alu_main ALUop" *)
  (* src = "alu/alu.v:8.32-8.37" *)
  wire [2:0] \alu_main.ALUop ;
  (* hdlname = "alu_main Adder_Result" *)
  (* src = "alu/alu.v:21.18-21.30" *)
  wire [31:0] \alu_main.Adder_Result ;
  (* hdlname = "alu_main And" *)
  (* src = "alu/alu.v:53.18-53.21" *)
  wire [31:0] \alu_main.And ;
  (* hdlname = "alu_main B" *)
  (* src = "alu/alu.v:7.23-7.24" *)
  wire [31:0] \alu_main.B ;
  (* hdlname = "alu_main Nor" *)
  (* src = "alu/alu.v:53.32-53.35" *)
  wire [31:0] \alu_main.Nor ;
  (* hdlname = "alu_main Or" *)
  (* src = "alu/alu.v:53.23-53.25" *)
  wire [31:0] \alu_main.Or ;
  (* hdlname = "alu_main Overflow" *)
  (* src = "alu/alu.v:9.31-9.39" *)
  wire \alu_main.Overflow ;
  (* hdlname = "alu_main Result" *)
  (* src = "alu/alu.v:12.22-12.28" *)
  wire [31:0] \alu_main.Result ;
  (* hdlname = "alu_main Slt" *)
  (* src = "alu/alu.v:24.18-24.21" *)
  wire \alu_main.Slt ;
  (* hdlname = "alu_main Sltu" *)
  (* src = "alu/alu.v:24.23-24.27" *)
  wire \alu_main.Sltu ;
  (* hdlname = "alu_main Xor" *)
  (* src = "alu/alu.v:53.27-53.30" *)
  wire [31:0] \alu_main.Xor ;
  (* hdlname = "alu_main Zero" *)
  (* src = "alu/alu.v:11.27-11.31" *)
  wire \alu_main.Zero ;
  (* hdlname = "alu_main addend" *)
  (* src = "alu/alu.v:18.18-18.24" *)
  wire [31:0] \alu_main.addend ;
  (* hdlname = "alu_main cout" *)
  (* src = "alu/alu.v:24.12-24.16" *)
  (* unused_bits = "0" *)
  wire \alu_main.cout ;
  (* hdlname = "alu_main sign_a" *)
  (* src = "alu/alu.v:27.7-27.13" *)
  wire \alu_main.sign_a ;
  (* hdlname = "alu_main sign_b" *)
  (* src = "alu/alu.v:27.28-27.34" *)
  wire \alu_main.sign_b ;
  (* hdlname = "alu_main sign_result" *)
  (* src = "alu/alu.v:27.15-27.26" *)
  wire \alu_main.sign_result ;
  (* hdlname = "alu_main sub" *)
  (* src = "alu/alu.v:24.7-24.10" *)
  wire \alu_main.sub ;
  (* src = "simple_cpu/simple_cpu.v:7.11-7.14" *)
  input clk;
  wire clk;
  (* onehot = 32'd1 *)
  reg [4:0] current_state;
  (* src = "simple_cpu/simple_cpu.v:118.37-118.46" *)
  wire [31:0] imm_Btype;
  (* src = "simple_cpu/simple_cpu.v:118.15-118.24" *)
  wire [31:0] imm_Itype;
  (* src = "simple_cpu/simple_cpu.v:118.59-118.68" *)
  wire [31:0] imm_Jtype;
  (* src = "simple_cpu/simple_cpu.v:118.26-118.35" *)
  wire [31:0] imm_Stype;
  (* src = "simple_cpu/simple_cpu.v:118.48-118.57" *)
  wire [31:0] imm_Utype;
  (* src = "simple_cpu/simple_cpu.v:167.14-167.28" *)
  wire [1:0] lower_two_bits;
  (* src = "simple_cpu/simple_cpu.v:54.15-54.21" *)
  reg [31:0] old_PC;
  (* src = "simple_cpu/simple_cpu.v:169.15-169.29" *)
  wire [31:0] read_data_dest;
  (* hdlname = "rf clk" *)
  (* src = "reg_file/reg_file.v:7.30-7.33" *)
  wire \rf.clk ;
  (* hdlname = "rf raddr1" *)
  (* src = "reg_file/reg_file.v:9.20-9.26" *)
  wire [4:0] \rf.raddr1 ;
  (* hdlname = "rf raddr2" *)
  (* src = "reg_file/reg_file.v:10.20-10.26" *)
  wire [4:0] \rf.raddr2 ;
  (* hdlname = "rf rdata1" *)
  (* src = "reg_file/reg_file.v:13.21-13.27" *)
  wire [31:0] \rf.rdata1 ;
  (* hdlname = "rf rdata2" *)
  (* src = "reg_file/reg_file.v:14.21-14.27" *)
  wire [31:0] \rf.rdata2 ;
  (* hdlname = "rf waddr" *)
  (* src = "reg_file/reg_file.v:8.20-8.25" *)
  wire [4:0] \rf.waddr ;
  (* hdlname = "rf wdata" *)
  (* src = "reg_file/reg_file.v:12.21-12.26" *)
  wire [31:0] \rf.wdata ;
  (* hdlname = "rf wen" *)
  (* src = "reg_file/reg_file.v:11.30-11.33" *)
  wire \rf.wen ;
  (* src = "simple_cpu/simple_cpu.v:8.11-8.14" *)
  input rst;
  wire rst;
  (* hdlname = "sft A" *)
  (* src = "shifter/shifter.v:6.20-6.21" *)
  wire [31:0] \sft.A ;
  (* hdlname = "sft B" *)
  (* src = "shifter/shifter.v:7.29-7.30" *)
  wire [4:0] \sft.B ;
  (* hdlname = "sft Lshift" *)
  (* src = "shifter/shifter.v:18.18-18.24" *)
  wire [31:0] \sft.Lshift ;
  (* hdlname = "sft Result" *)
  (* src = "shifter/shifter.v:9.20-9.26" *)
  wire [31:0] \sft.Result ;
  (* hdlname = "sft Rshift" *)
  (* src = "shifter/shifter.v:18.26-18.32" *)
  wire [31:0] \sft.Rshift ;
  (* hdlname = "sft Rshift_ext" *)
  (* src = "shifter/shifter.v:19.19-19.29" *)
  (* unused_bits = "32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63" *)
  wire [63:0] \sft.Rshift_ext ;
  (* hdlname = "sft Shiftop" *)
  (* src = "shifter/shifter.v:8.29-8.36" *)
  wire [1:0] \sft.Shiftop ;
  (* hdlname = "sft add_bit" *)
  (* src = "shifter/shifter.v:15.7-15.14" *)
  wire \sft.add_bit ;
  (* src = "simple_cpu/simple_cpu.v:140.14-140.19" *)
  wire [4:0] shamt;
  (* src = "simple_cpu/simple_cpu.v:149.8-149.20" *)
  wire shift_select;
  (* hdlname = "rf mem" *)
  (* src = "reg_file/reg_file.v:18.17-18.20" *)
  reg [31:0] \rf.mem  [31:0];
  always @(posedge clk) begin
    if (_044_[31])
      \rf.mem [_042_] <= _043_;
  end
  assign _047_ = \rf.mem [Instruction_reg[24:20]];
  assign _046_ = \rf.mem [Instruction_reg[19:15]];
  assign _000_ = old_PC + (* src = "simple_cpu/simple_cpu.v:193.41-193.51" *) 32'd4;
  assign _001_ = PC_reg + (* src = "simple_cpu/simple_cpu.v:281.23-281.41" *) { Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[7], Instruction_reg[30:25], Instruction_reg[11:8], 1'h0 };
  assign _002_ = PC_reg + (* src = "simple_cpu/simple_cpu.v:284.21-284.39" *) { Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[19:12], Instruction_reg[20], Instruction_reg[30:21], 1'h0 };
  assign _003_ = PC_reg + (* src = "simple_cpu/simple_cpu.v:290.21-290.27" *) 32'd4;
  (* src = "simple_cpu/simple_cpu.v:272.3-294.6" *)
  always @(posedge clk)
    if (rst) old_PC <= 32'd0;
    else if (current_state[3]) old_PC <= PC_reg;
  (* src = "simple_cpu/simple_cpu.v:272.3-294.6" *)
  always @(posedge clk)
    if (rst) PC_reg <= 32'd0;
    else if (current_state[3]) PC_reg <= _078_;
  (* src = "simple_cpu/simple_cpu.v:261.3-267.6" *)
  always @(posedge clk)
    if (rst) Instruction_reg <= 32'd0;
    else if (current_state[0]) Instruction_reg <= Instruction;
  (* src = "simple_cpu/simple_cpu.v:252.3-258.6" *)
  always @(posedge clk)
    if (rst) Read_data_reg <= 32'd0;
    else if (MemRead) Read_data_reg <= Read_data;
  (* src = "simple_cpu/simple_cpu.v:243.3-249.6" *)
  always @(posedge clk)
    if (rst) ALU_Shifter_Result_reg <= 32'd0;
    else if (_070_) ALU_Shifter_Result_reg <= ALU_Shifter_Result;
  assign _004_ = _012_ & current_state[3];
  assign _005_ = _013_ & current_state[2];
  assign _006_ = _014_ & current_state[3];
  assign _007_ = _015_ & current_state[4];
  assign _008_ = _015_ & current_state[0];
  assign _009_ = _016_ & current_state[3];
  assign _010_ = _017_ & current_state[2];
  assign _011_[1] = | { _005_, _004_ };
  assign _011_[0] = | { _010_, _009_, current_state[1], rst };
  always @(posedge clk)
    current_state <= { _008_, _007_, _006_, _011_[1:0] };
  assign _012_ = ! { _056_, Btype, rst };
  assign _013_ = ! { Store, rst };
  assign _014_ = { _056_, Btype, rst } == 3'h4;
  assign _015_ = ~ rst;
  assign _016_ = { Btype, rst } == 2'h2;
  assign _017_ = { Store, rst } == 2'h2;
  assign LUI = Instruction_reg[6:0] == (* src = "simple_cpu/simple_cpu.v:107.18-107.48" *) 7'h37;
  assign AUIPC = Instruction_reg[6:0] == (* src = "simple_cpu/simple_cpu.v:108.18-108.50" *) 7'h17;
  assign JAL = Instruction_reg[6:0] == (* src = "simple_cpu/simple_cpu.v:109.18-109.48" *) 7'h6f;
  assign JALR = Instruction_reg[6:0] == (* src = "simple_cpu/simple_cpu.v:110.18-110.49" *) 7'h67;
  assign Btype = Instruction_reg[6:0] == (* src = "simple_cpu/simple_cpu.v:111.18-111.50" *) 7'h63;
  assign Load = Instruction_reg[6:0] == (* src = "simple_cpu/simple_cpu.v:112.18-112.49" *) 7'h03;
  assign Store = Instruction_reg[6:0] == (* src = "simple_cpu/simple_cpu.v:113.18-113.50" *) 7'h23;
  assign Itype = Instruction_reg[6:0] == (* src = "simple_cpu/simple_cpu.v:114.18-114.50" *) 7'h13;
  assign Rtype = Instruction_reg[6:0] == (* src = "simple_cpu/simple_cpu.v:115.18-115.50" *) 7'h33;
  assign _018_ = Instruction_reg[14:12] == (* src = "simple_cpu/simple_cpu.v:150.46-150.78" *) 3'h1;
  assign _019_ = Instruction_reg[14:12] == (* src = "simple_cpu/simple_cpu.v:150.82-150.114" *) 3'h5;
  assign _020_ = ! (* src = "simple_cpu/simple_cpu.v:175.28-175.60" *) Instruction_reg[14:12];
  assign _021_ = ! (* src = "simple_cpu/simple_cpu.v:175.66-175.89" *) ALU_Shifter_Result_reg[1:0];
  assign _022_ = ALU_Shifter_Result_reg[1:0] == (* src = "simple_cpu/simple_cpu.v:175.140-175.163" *) 2'h1;
  assign _023_ = ALU_Shifter_Result_reg[1:0] == (* src = "simple_cpu/simple_cpu.v:175.216-175.239" *) 2'h2;
  assign _024_ = ALU_Shifter_Result_reg[1:0] == (* src = "simple_cpu/simple_cpu.v:175.293-175.316" *) 2'h3;
  assign _025_ = Instruction_reg[14:12] == (* src = "simple_cpu/simple_cpu.v:177.9-177.41" *) 3'h2;
  assign _026_ = Instruction_reg[14:12] == (* src = "simple_cpu/simple_cpu.v:178.9-178.41" *) 3'h4;
  assign _027_ = Instruction_reg[14:12] == (* src = "simple_cpu/simple_cpu.v:209.9-209.41" *) 3'h6;
  assign _028_ = Instruction_reg[14:12] == (* src = "simple_cpu/simple_cpu.v:210.9-210.41" *) 3'h7;
  assign _029_ = \alu_main.A  + (* src = "alu/alu.v:38.32-38.42" *) \alu_main.addend ;
  assign { \alu_main.cout , \alu_main.Adder_Result  } = _029_ + (* src = "alu/alu.v:38.32-38.48" *) \alu_main.sub ;
  assign \alu_main.Overflow  = _033_ & (* src = "alu/alu.v:44.20-44.72" *) _039_;
  assign \alu_main.And  = \alu_main.A  & (* src = "alu/alu.v:54.15-54.20" *) \alu_main.B ;
  assign _030_ = \alu_main.ALUop  == (* src = "alu/alu.v:32.16-32.31" *) 3'h1;
  assign _031_ = \alu_main.ALUop [2:1] == (* src = "alu/alu.v:32.37-32.56" *) 2'h1;
  assign ALU_Zero = ! (* src = "alu/alu.v:73.16-73.24" *) ALU_Result;
  assign \alu_main.sub  = _030_ || (* src = "alu/alu.v:32.15-32.57" *) _031_;
  assign _032_ = ~ (* src = "alu/alu.v:35.26-35.29" *) \alu_main.B ;
  assign _033_ = ~ (* src = "alu/alu.v:44.20-44.47" *) _040_;
  assign \alu_main.Nor  = ~ (* src = "alu/alu.v:57.15-57.23" *) \alu_main.Or ;
  assign \alu_main.Or  = \alu_main.A  | (* src = "alu/alu.v:55.14-55.19" *) \alu_main.B ;
  assign \alu_main.addend  = \alu_main.sub  ? (* src = "alu/alu.v:35.18-35.33" *) _032_ : \alu_main.B ;
  assign \alu_main.Sltu  = _041_ ? (* src = "alu/alu.v:49.16-49.56" *) \alu_main.B [31] : \alu_main.Adder_Result [31];
  assign _034_ = \alu_main.ALUop [0] ? (* src = "alu/alu.v:69.46-69.67" *) \alu_main.And  : \alu_main.Or ;
  assign _035_ = \alu_main.ALUop [0] ? (* src = "alu/alu.v:69.72-69.94" *) \alu_main.Nor  : \alu_main.Xor ;
  assign _036_ = \alu_main.ALUop [1] ? (* src = "alu/alu.v:69.32-69.95" *) _034_ : _035_;
  assign ALU_Result = \alu_main.ALUop [2] ? (* src = "alu/alu.v:69.18-70.61" *) _036_ : _038_;
  assign _037_ = \alu_main.ALUop [0] ? (* src = "alu/alu.v:70.22-70.45" *) \alu_main.Sltu  : \alu_main.Slt ;
  assign _038_ = \alu_main.ALUop [1] ? (* src = "alu/alu.v:70.7-70.60" *) { 31'h00000000, _037_ } : \alu_main.Adder_Result ;
  assign _039_ = \alu_main.A [31] ^ (* src = "alu/alu.v:44.51-44.71" *) \alu_main.Adder_Result [31];
  assign _040_ = \alu_main.A [31] ^ (* src = "alu/alu.v:44.23-44.46" *) \alu_main.addend [31];
  assign \alu_main.Slt  = \alu_main.Overflow  ^ (* src = "alu/alu.v:47.15-47.37" *) \alu_main.Adder_Result [31];
  assign _041_ = \alu_main.A [31] ^ (* src = "alu/alu.v:49.17-49.32" *) \alu_main.B [31];
  assign \alu_main.Xor  = \alu_main.A  ^ (* src = "alu/alu.v:56.15-56.20" *) \alu_main.B ;
  assign _045_ = \rf.wen  && (* src = "reg_file/reg_file.v:22.7-22.19" *) Instruction_reg[11:7];
  assign _048_ = | (* src = "reg_file/reg_file.v:28.18-28.47" *) Instruction_reg[19:15];
  assign _049_ = | (* src = "reg_file/reg_file.v:29.18-29.47" *) Instruction_reg[24:20];
  assign RF_rdata1 = _048_ ? (* src = "reg_file/reg_file.v:28.18-28.47" *) _046_ : 32'd0;
  assign RF_rdata2 = _049_ ? (* src = "reg_file/reg_file.v:29.18-29.47" *) _047_ : 32'd0;
  assign \sft.add_bit  = Instruction_reg[30] & (* src = "shifter/shifter.v:16.19-16.41" *) \alu_main.A [31];
  assign \sft.Lshift  = \alu_main.A  << (* src = "shifter/shifter.v:22.18-22.24" *) \sft.B ;
  assign \sft.Rshift_ext  = { \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \sft.add_bit , \alu_main.A  } >> (* src = "shifter/shifter.v:24.22-24.45" *) \sft.B ;
  assign Shifter_Result = Instruction_reg[14] ? (* src = "shifter/shifter.v:28.18-28.48" *) \sft.Rshift_ext [31:0] : \sft.Lshift ;
  assign shift_select = _051_ && (* src = "simple_cpu/simple_cpu.v:150.25-150.115" *) _052_;
  assign MemRead = Load && (* src = "simple_cpu/simple_cpu.v:174.20-174.52" *) current_state[2];
  assign MemWrite = Store && (* src = "simple_cpu/simple_cpu.v:181.21-181.54" *) current_state[2];
  assign \rf.wen  = _064_ && (* src = "simple_cpu/simple_cpu.v:190.20-190.100" *) current_state[1];
  assign _050_ = Btype && (* src = "simple_cpu/simple_cpu.v:279.13-279.42" *) Branch_condition_met;
  assign _051_ = Rtype || (* src = "simple_cpu/simple_cpu.v:150.26-150.40" *) Itype;
  assign _052_ = _018_ || (* src = "simple_cpu/simple_cpu.v:150.46-150.114" *) _019_;
  assign _053_ = Rtype || (* src = "simple_cpu/simple_cpu.v:153.20-153.34" *) Btype;
  assign _054_ = Itype || (* src = "simple_cpu/simple_cpu.v:154.26-154.39" *) Load;
  assign _055_ = _054_ || (* src = "simple_cpu/simple_cpu.v:154.26-154.47" *) JALR;
  assign _056_ = Store || (* src = "simple_cpu/simple_cpu.v:158.30-158.43" *) Load;
  assign _057_ = _056_ || (* src = "simple_cpu/simple_cpu.v:158.30-158.51" *) JALR;
  assign _058_ = _057_ || (* src = "simple_cpu/simple_cpu.v:158.30-158.60" *) AUIPC;
  assign _059_ = _058_ || (* src = "simple_cpu/simple_cpu.v:158.30-158.67" *) LUI;
  assign _060_ = _051_ || (* src = "simple_cpu/simple_cpu.v:190.21-190.43" *) Load;
  assign _061_ = _060_ || (* src = "simple_cpu/simple_cpu.v:190.21-190.51" *) JALR;
  assign _062_ = _061_ || (* src = "simple_cpu/simple_cpu.v:190.21-190.58" *) JAL;
  assign _063_ = _062_ || (* src = "simple_cpu/simple_cpu.v:190.21-190.67" *) AUIPC;
  assign _064_ = _063_ || (* src = "simple_cpu/simple_cpu.v:190.21-190.74" *) LUI;
  assign _065_ = LUI || (* src = "simple_cpu/simple_cpu.v:191.24-191.36" *) AUIPC;
  assign _066_ = _065_ || (* src = "simple_cpu/simple_cpu.v:191.24-191.45" *) Itype;
  assign _067_ = _066_ || (* src = "simple_cpu/simple_cpu.v:191.24-191.54" *) Rtype;
  assign _068_ = JALR || (* src = "simple_cpu/simple_cpu.v:193.26-193.37" *) JAL;
  assign _069_ = current_state[3] || (* src = "simple_cpu/simple_cpu.v:246.18-246.61" *) current_state[4];
  assign _070_ = _069_ || (* src = "simple_cpu/simple_cpu.v:246.18-246.84" *) current_state[0];
  assign _071_ = ~ (* src = "simple_cpu/simple_cpu.v:157.83-157.103" *) Instruction_reg[14];
  assign _072_ = ~ (* src = "simple_cpu/simple_cpu.v:206.45-206.54" *) ALU_Zero;
  assign _073_ = ~ (* src = "simple_cpu/simple_cpu.v:208.45-208.59" *) ALU_Result[0];
  assign _074_ = Instruction_reg[13] | (* src = "simple_cpu/simple_cpu.v:157.61-157.103" *) _071_;
  assign _075_ = Instruction_reg[12] | (* src = "simple_cpu/simple_cpu.v:159.64-159.111" *) Instruction_reg[30];
  assign _044_[31] = _045_ ? (* full_case = 32'd1 *) (* src = "reg_file/reg_file.v:22.3-24.6" *) 1'h1 : 1'h0;
  assign _043_ = _045_ ? (* full_case = 32'd1 *) (* src = "reg_file/reg_file.v:22.3-24.6" *) RF_wdata : 32'hxxxxxxxx;
  assign _042_ = _045_ ? (* full_case = 32'd1 *) (* src = "reg_file/reg_file.v:22.3-24.6" *) Instruction_reg[11:7] : 5'hxx;
  assign _076_ = JALR ? (* full_case = 32'd1 *) (* src = "simple_cpu/simple_cpu.v:285.22-285.26|simple_cpu/simple_cpu.v:285.18-291.12" *) { ALU_Shifter_Result_reg[31:1], 1'h0 } : _003_;
  assign _077_ = JAL ? (* full_case = 32'd1 *) (* src = "simple_cpu/simple_cpu.v:282.22-282.25|simple_cpu/simple_cpu.v:282.18-291.12" *) _002_ : _076_;
  assign _078_ = _050_ ? (* full_case = 32'd1 *) (* src = "simple_cpu/simple_cpu.v:279.13-279.42|simple_cpu/simple_cpu.v:279.9-291.12" *) _001_ : _077_;
  assign _079_ = { 24'h000000, RF_rdata2[7:0] } << (* src = "simple_cpu/simple_cpu.v:182.61-182.189" *) _105_;
  assign _080_ = { 16'h0000, RF_rdata2[15:0] } << (* src = "simple_cpu/simple_cpu.v:183.64-183.122" *) { ALU_Shifter_Result_reg[1], 4'h0 };
  assign _081_ = 4'h1 << (* src = "simple_cpu/simple_cpu.v:185.61-185.86" *) ALU_Shifter_Result_reg[1:0];
  assign _082_ = LUI ? (* src = "simple_cpu/simple_cpu.v:152.45-152.70" *) 32'd0 : RF_rdata1;
  assign \alu_main.A  = AUIPC ? (* src = "simple_cpu/simple_cpu.v:152.26-152.70" *) old_PC : _082_;
  assign \alu_main.B  = _053_ ? (* src = "simple_cpu/simple_cpu.v:153.19-156.34" *) RF_rdata2 : _083_;
  assign _083_ = _055_ ? (* src = "simple_cpu/simple_cpu.v:154.25-156.34" *) { Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31:20] } : _084_;
  assign _084_ = Store ? (* src = "simple_cpu/simple_cpu.v:155.25-156.34" *) { Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31:25], Instruction_reg[11:7] } : { Instruction_reg[31:12], 12'h000 };
  assign \alu_main.ALUop  = Btype ? (* src = "simple_cpu/simple_cpu.v:157.23-159.137" *) { 1'h0, Instruction_reg[14], _074_ } : _085_;
  assign _085_ = _059_ ? (* src = "simple_cpu/simple_cpu.v:158.29-159.137" *) 3'h0 : _086_;
  assign _086_ = Rtype ? (* src = "simple_cpu/simple_cpu.v:159.29-159.137" *) { Instruction_reg[14:13], _075_ } : Instruction_reg[14:12];
  assign \sft.B  = Rtype ? (* src = "simple_cpu/simple_cpu.v:161.22-161.54" *) RF_rdata2[4:0] : Instruction_reg[24:20];
  assign read_data_dest = _020_ ? (* src = "simple_cpu/simple_cpu.v:175.27-179.177" *) _090_ : _091_;
  assign _087_ = _024_ ? (* src = "simple_cpu/simple_cpu.v:175.292-175.374" *) { Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31:24] } : 32'd0;
  assign _088_ = _023_ ? (* src = "simple_cpu/simple_cpu.v:175.215-175.374" *) { Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23], Read_data_reg[23:16] } : _087_;
  assign _089_ = _022_ ? (* src = "simple_cpu/simple_cpu.v:175.139-175.374" *) { Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15:8] } : _088_;
  assign _090_ = _021_ ? (* src = "simple_cpu/simple_cpu.v:175.65-175.374" *) { Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7], Read_data_reg[7:0] } : _089_;
  assign _091_ = _018_ ? (* src = "simple_cpu/simple_cpu.v:176.8-179.176" *) _093_ : _094_;
  assign _092_ = _023_ ? (* src = "simple_cpu/simple_cpu.v:176.122-176.204" *) { Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31], Read_data_reg[31:16] } : 32'd0;
  assign _093_ = _021_ ? (* src = "simple_cpu/simple_cpu.v:176.46-176.204" *) { Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15], Read_data_reg[15:0] } : _092_;
  assign _094_ = _025_ ? (* src = "simple_cpu/simple_cpu.v:177.8-179.175" *) Read_data_reg : _098_;
  assign _095_ = _023_ ? (* src = "simple_cpu/simple_cpu.v:178.157-178.263" *) Read_data_reg[23:16] : _099_;
  assign _096_ = _022_ ? (* src = "simple_cpu/simple_cpu.v:178.107-178.263" *) Read_data_reg[15:8] : _095_;
  assign _097_ = _021_ ? (* src = "simple_cpu/simple_cpu.v:178.58-178.263" *) Read_data_reg[7:0] : _096_;
  assign _098_ = _026_ ? (* src = "simple_cpu/simple_cpu.v:178.8-179.174" *) { 24'h000000, _097_ } : _102_;
  assign _099_ = _024_ ? (* src = "simple_cpu/simple_cpu.v:178.208-178.263" *) Read_data_reg[31:24] : 8'h00;
  assign _100_ = _023_ ? (* src = "simple_cpu/simple_cpu.v:179.108-179.164" *) Read_data_reg[31:16] : 16'h0000;
  assign _101_ = _021_ ? (* src = "simple_cpu/simple_cpu.v:179.58-179.164" *) Read_data_reg[15:0] : _100_;
  assign _102_ = _019_ ? (* src = "simple_cpu/simple_cpu.v:179.8-179.173" *) { 16'h0000, _101_ } : 32'd0;
  assign _103_ = _023_ ? (* src = "simple_cpu/simple_cpu.v:182.153-182.188" *) 32'd16 : 32'd24;
  assign _104_ = _022_ ? (* src = "simple_cpu/simple_cpu.v:182.121-182.188" *) 32'd8 : _103_;
  assign _105_ = _021_ ? (* src = "simple_cpu/simple_cpu.v:182.89-182.188" *) 32'd0 : _104_;
  assign Write_data = _020_ ? (* src = "simple_cpu/simple_cpu.v:182.23-184.61" *) _079_ : _107_;
  assign _106_ = ALU_Shifter_Result_reg[0] ? (* src = "simple_cpu/simple_cpu.v:183.45-183.131" *) 32'd0 : _080_;
  assign _107_ = _018_ ? (* src = "simple_cpu/simple_cpu.v:183.7-184.61" *) _106_ : _108_;
  assign _108_ = _025_ ? (* src = "simple_cpu/simple_cpu.v:184.7-184.61" *) RF_rdata2 : 32'd0;
  assign Write_strb = _020_ ? (* src = "simple_cpu/simple_cpu.v:185.23-187.58" *) _081_ : _111_;
  assign _109_ = ALU_Shifter_Result_reg[1] ? (* src = "simple_cpu/simple_cpu.v:186.64-186.101" *) 4'hc : 4'h3;
  assign _110_ = ALU_Shifter_Result_reg[0] ? (* src = "simple_cpu/simple_cpu.v:186.45-186.112" *) 4'h0 : _109_;
  assign _111_ = _018_ ? (* src = "simple_cpu/simple_cpu.v:186.7-187.58" *) _110_ : _112_;
  assign _112_ = _025_ ? (* src = "simple_cpu/simple_cpu.v:187.7-187.58" *) 4'hf : 4'h0;
  assign RF_wdata = _067_ ? (* src = "simple_cpu/simple_cpu.v:191.23-193.59" *) ALU_Shifter_Result_reg : _113_;
  assign _113_ = Load ? (* src = "simple_cpu/simple_cpu.v:192.25-193.59" *) read_data_dest : _114_;
  assign _114_ = _068_ ? (* src = "simple_cpu/simple_cpu.v:193.25-193.59" *) _000_ : 32'd0;
  assign ALU_Shifter_Result = shift_select ? (* src = "simple_cpu/simple_cpu.v:201.31-201.73" *) Shifter_Result : ALU_Result;
  assign Branch_condition_met = _020_ ? (* src = "simple_cpu/simple_cpu.v:205.33-210.71" *) ALU_Zero : _115_;
  assign _115_ = _018_ ? (* src = "simple_cpu/simple_cpu.v:206.8-210.70" *) _072_ : _116_;
  assign _116_ = _026_ ? (* src = "simple_cpu/simple_cpu.v:207.8-210.69" *) ALU_Result[0] : _117_;
  assign _117_ = _019_ ? (* src = "simple_cpu/simple_cpu.v:208.8-210.68" *) _073_ : _118_;
  assign _118_ = _027_ ? (* src = "simple_cpu/simple_cpu.v:209.8-210.67" *) ALU_Result[0] : _119_;
  assign _119_ = _028_ ? (* src = "simple_cpu/simple_cpu.v:210.8-210.66" *) _073_ : 1'h0;
  assign _011_[4:2] = { _008_, _007_, _006_ };
  assign _044_[30:0] = { _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31] };
  assign ALU_A = \alu_main.A ;
  assign ALU_ALUop = \alu_main.ALUop ;
  assign ALU_B = \alu_main.B ;
  assign ALU_Overflow = \alu_main.Overflow ;
  assign ALU_Shifter_A = \alu_main.A ;
  assign Address = { ALU_Shifter_Result_reg[31:2], 2'h0 };
  assign PC = PC_reg;
  assign RF_radder1 = Instruction_reg[19:15];
  assign RF_radder2 = Instruction_reg[24:20];
  assign RF_waddr = Instruction_reg[11:7];
  assign RF_wen = \rf.wen ;
  assign Shifter_A = \alu_main.A ;
  assign Shifter_B = \sft.B ;
  assign Shifter_Shiftop = { Instruction_reg[14], Instruction_reg[30] };
  assign \alu_main.Result  = ALU_Result;
  assign \alu_main.Zero  = ALU_Zero;
  assign \alu_main.sign_a  = \alu_main.A [31];
  assign \alu_main.sign_b  = \alu_main.B [31];
  assign \alu_main.sign_result  = \alu_main.Adder_Result [31];
  assign imm_Btype = { Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[7], Instruction_reg[30:25], Instruction_reg[11:8], 1'h0 };
  assign imm_Itype = { Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31:20] };
  assign imm_Jtype = { Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[19:12], Instruction_reg[20], Instruction_reg[30:21], 1'h0 };
  assign imm_Stype = { Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31], Instruction_reg[31:25], Instruction_reg[11:7] };
  assign imm_Utype = { Instruction_reg[31:12], 12'h000 };
  assign lower_two_bits = ALU_Shifter_Result_reg[1:0];
  assign \rf.clk  = clk;
  assign \rf.raddr1  = Instruction_reg[19:15];
  assign \rf.raddr2  = Instruction_reg[24:20];
  assign \rf.rdata1  = RF_rdata1;
  assign \rf.rdata2  = RF_rdata2;
  assign \rf.waddr  = Instruction_reg[11:7];
  assign \rf.wdata  = RF_wdata;
  assign \sft.A  = \alu_main.A ;
  assign \sft.Result  = Shifter_Result;
  assign \sft.Rshift  = \sft.Rshift_ext [31:0];
  assign \sft.Shiftop  = { Instruction_reg[14], Instruction_reg[30] };
  assign shamt = Instruction_reg[24:20];
endmodule
